# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7112a370778f62ae0818659ff1c3b69eeada5a90646655d39d0af02c9227e7391bc5e43ec4e360858a66267ec6b78e8d69678c1083af04a0458c503ad177f06

test:
  secret_key_base: ac685071bdef2fa415f8c20c0038d1f8615cb0d1f55049935a964c80c0d5eebd77275ad5b10076a9576da1826039f3a85fa4fab964d94a16e73bd5bc43d80316

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
